name: docker obs image

# Déclenchement du workflow à chaque push sur la branche 'main'
on:
  push:
    branches:
      - main  # Vous pouvez également ajouter d'autres branches comme 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest  # Cette action s'exécutera sur un environnement Ubuntu

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker Buildx (facultatif mais recommandé pour une construction plus rapide)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Se connecter au GitHub Container Registry avec le token GitHub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io #Spécifie le github conatiner registry
          username: ${{ secrets.USER_GIT }}  # Utilise le nom d'utilisateur GitHub
          password: ${{ secrets.GCR_TOKEN }}  # Utilise le secret GitHub Token pour l'authentification

      # Étape 4 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository | toLowercase() }}/obs-docker-image:v1.0 ./kasmimages

      # Étape 5 : Pousser l'image Docker vers GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository | toLowercase() }}/obs-docker-image:v1.0 
