name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenchement du workflow à chaque push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Cette action s'exécutera sur un environnement Ubuntu

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Se connecter au GitHub Container Registry avec le token GitHub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # Spécifie le GitHub Container Registry
          username: ${{ secrets.USER_GIT }}  # Utilise votre nom d'utilisateur GitHub
          password: ${{ secrets.GCR_TOKEN }}  # Utilise le secret GitHub Token pour l'authentification

      # Étape 4 : Convertir le nom du dépôt en minuscules
      - name: Set repository name to lowercase
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Étape 5 : Construire l'image Docker avec le tag v1.0
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}/obs-docker-image:v1.0 ./kasmimages

      # Étape 6 : Pousser l'image Docker vers GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}/obs-docker-image:v1.0
